BetaEventTag:
        FilePath: /nics/b/home/ryokoyam/vandle_work/event_lists/
        Nuclides:
                - "Ga87"
                - "Ga86"
                - "Ga85"
                - "Ga84"
                - "Ga83"
                - "Ni79"
                - "Ni78"
                - "Ni77"
                - "Ni76"
                - "Ni75"
                - "Cu82"
                - "Cu81"
                - "Cu80"
                - "Cu79"
                - "Cu78"
                - "Cu77"
                - "Zn84"
                - "Zn83"
                - "Zn82"
                - "Zn81"
                - "Zn80"
                - "Co73"
                - "Co74"
                - "Co75"
                - "As88"
                - "As89"
                - "As90"
                - "As91"
                - "Ge85"
                - "Ge86"
                - "Ge87"
                - "Ge88"
                - "Ge89"

