AnamergerMain:
  MergerListName: /nics/b/home/ryokoyam/vandle_work/anamergerLists/anamergerListCu78.txt
  NumWorkers: 38
  PrintFrequency: 10000
  TimeWindow: '1.0'
  TreeName: mergedCorrectedBeta
  UseProof: true
