AnamergerMain:
  MergerListName: /nics/b/home/ryokoyam/vandle_work/anamergerLists/anamergerListZn83.txt
  NumWorkers: 38
  PrintFrequency: 10000
  TimeWindow: '0.2'
  TreeName: mergedCorrectedBeta
  UseProof: true
