AnamergerMain:
  MergerListName: /nics/b/home/ryokoyam/vandle_work/anamergerLists/anamergerListAs88.txt
  NumWorkers: 38
  PrintFrequency: 10000
  TimeWindow: '0.6'
  TreeName: mergedCorrectedBeta
  UseProof: true
