AnamergerMain:
  MergerListName: /nics/b/home/ryokoyam/vandle_work/anamergerLists/anamergerListCo74.txt
  NumWorkers: 38
  PrintFrequency: 10000
  TimeWindow: '0.10'
  TreeName: mergedCorrectedBeta
  UseProof: true
