AnamergerMain:
  MergerListName: /nics/b/home/ryokoyam/vandle_work/anamergerLists/anamergerListNi77.txt
  NumWorkers: 38
  PrintFrequency: 10000
  TimeWindow: '0.5'
  TreeName: mergedCorrectedBeta
  UseProof: true
