AnamergerMain:
  MergerListName: /nics/b/home/ryokoyam/vandle_work/anamergerLists/anamergerListCo75.txt
  NumWorkers: 38
  PrintFrequency: 10000
  TimeWindow: '0.08'
  TreeName: mergedCorrectedBeta
  UseProof: true
