AnamergerMain:
  MergerListName: /nics/b/home/ryokoyam/vandle_work/anamergerLists/anamergerListNi78.txt
  NumWorkers: 38
  PrintFrequency: 10000
  TimeWindow: '0.3'
  TreeName: mergedCorrectedBeta
  UseProof: False
