AnamergerMain:
  MergerListName: /nics/b/home/ryokoyam/vandle_work/anamergerLists/anamergerListCo73.txt
  NumWorkers: 38
  PrintFrequency: 10000
  TimeWindow: '0.12'
  TreeName: mergedCorrectedBeta
  UseProof: true
