MergerMain:
  # TCutGFileName: referenceCuts.root
  # PIDCuts:
  #  - "17N"

E19044BetaTSScannor:
  InputFileName: output.root
  TreeName: pspmt
  PixieBranchName: pspmt_compressed
  MinHighGainDynEnergy: 10
  MaxHighGainDynEnergy: 30000
  MinLowGainDynEnergy: -2000
  MaxLowGainDynEnergy: 2000
  FITThreshold: 0

  OtherBranches:
    - "vandle_vec_"
    - "clover_vec_"
#  FirstEntry: 0
#  LastEntry: 10000

ImplantTSScannor:
  InputFileName: output.root
  TreeName: pspmt
  PixieBranchName: pspmt_compressed
  MinLowGainDynEnergy: 5000
  MaxLowGainDynEnergy: 65535
  OtherBranches:
    - "clover_vec_"
    - "pid_vec_"
#  FirstEntry: 0
#  LastEntry: 10000

E19044NEXTTSScannor:
  InputFileName: 252cf_test_DD.root
  TreeName: PixTree
  PixieBranchName: PixTreeEvent
#  FirstEntry: 0
#  LastEntry: 1000

E19044VANDLETSScannor:
  InputFileName: mergedBeta.root
  TreeName: mergedBeta
  PixieBranchName: mergedBeta
#  FirstEntry: 0
#  LastEntry: 1000

E19044BetaTreeMerger:
  OutputFileName: mergedBeta.root
  TreeName: mergedBeta
  BranchName: mergedBeta
  ClassName: E19044Output
  PrintFrequency: 1000

  # +-1 sec
  TimeWindowLow: 100000000
  TimeWindowUp: 100000000

NEXTMerger:
  OutputFileName: mergedNEXTBeta.root
  TreeName: mergedNEXTBeta
  BranchName: mergedNEXTBeta
  ClassName: NEXTOutput
  PrintFrequency: 1000

BetaTreeMerger:
  #YSOMapFile: "./yso_map.txt"
  #NumberOfDivisions: 10
  CorrelationRadius: 0.2
