PspmtAnalyzer:
  CloverVec: true
  HighGainThreshold: -100
  LowGainThreshold: -900
  TimeOffset: 0
  TimeOffsetDeSi: -840
  TimeOffsetF11: 150
  TimeOffsetIon: -840
  TimeOffsetVeto: -840
  TimeWindow: 160
  TimeWindowDeSi: 50
  TimeWindowF11: 50
  TimeWindowIon: 50
  TimeWindowVeto: 50
  TraceMaxQDCRatioB: 0
  TraceMaxQDCRatioXA: 8000
  TraceMaxQDCRatioXB: 8000
  TraceMaxQDCRatioYA: 8000
  TraceMaxQDCRatioYB: 8000
  TreeName: pspmt
  VANDLEVec: true
  GammaScintVec: true
  YSOMapFile: "./config/YSO_2D_map.txt"
  NumberOfDivisions: 10
RunSetting:
  InitalEvent: 0
  PrintFrequency: 100000
  TChainFlag: true
TraceAnalyzer:
  ChannelList:
  - Channel:
      SubtypeName: dynode_high
      TagName: ignore
      TreeName: dynode_high
  - Channel:
      SubtypeName: anode_high
      TagName: xa
      TreeName: xa_high
  - Channel:
      SubtypeName: anode_high
      TagName: xb
      TreeName: xb_high
  - Channel:
      SubtypeName: anode_high
      TagName: ya
      TreeName: ya_high
  - Channel:
      SubtypeName: anode_high
      TagName: yb
      TreeName: yb_high
  - Channel:
      SubtypeName: dynode_low
      TagName: ignore
      TreeName: dynode_low
  - Channel:
      SubtypeName: anode_low
      TagName: xa
      TreeName: xa_low
  - Channel:
      SubtypeName: anode_low
      TagName: xb
      TreeName: xb_low
  - Channel:
      SubtypeName: anode_low
      TagName: ya
      TreeName: ya_low
  - Channel:
      SubtypeName: anode_low
      TagName: yb
      TreeName: yb_low
  - Channel:
      SubtypeName: desi
      TagName: top
      TreeName: desi_top
  - Channel:
      SubtypeName: desi
      TagName: bottom
      TreeName: desi_bottom
  - Channel:
      SubtypeName: veto
      TagName: '1'
      TreeName: veto_first
  - Channel:
      SubtypeName: veto
      TagName: '2'
      TreeName: veto_second
  - Channel:
      SubtypeName: ion
      TagName: white
      TreeName: ion_white
  - Channel:
      SubtypeName: ion
      TagName: green
      TreeName: ion_green
  - Channel:
      SubtypeName: ion
      TagName: blue
      TreeName: ion_blue
  - Channel:
      SubtypeName: ion
      TagName: black
      TreeName: ion_black
  - Channel:
      SubtypeName: f11
      TagName: left
      TreeName: f11_left
  - Channel:
      SubtypeName: f11
      TagName: right
      TreeName: f11_right
  - Channel:
      SubtypeName: dynode_high
      TagName: singles
      TreeName: dynode_singles
  ChannelOutput: false
